apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kavak-chatbot-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - kavaktest.nomada.dev
    secretName: kavak-chatbot-tls
  rules:
  - host: kavaktest.nomada.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kavak-chatbot-service
            port:
              number: 80
